#FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 AS build-env
FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim-arm32v7 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet publish DeviceStreamProxyModule -c Release -o out -r linux-arm

FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "DeviceStreamProxyModule.dll"]
