FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet publish DeviceStreamAgent -c Release -o out -r linux-arm

FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

ENTRYPOINT ["dotnet", "DeviceStreamAgent.dll"]
